name: 'publish'

on: [push]

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-15-intel' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-24.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - uses: Swatinem/rust-cache@v2
        with: 
          workspaces: "src-tauri -> target"
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: run linux script
        if: startsWith(matrix.platform, 'ubuntu')
        run: bash scripts/build/linux.sh

      - name: run macos script
        if: startsWith(matrix.platform, 'macos')
        run: bash scripts/build/macos.sh

      - name: run windows script(powershell)
        if: startsWith(matrix.platform, 'windows')
        run: pwsh scripts/build/windows.ps1

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}